version: '3'

networks:
  transcendance:

services:
  api:
    build:
      dockerfile: ./Dockerfile
      context: ./srcs/nestjs-backend
    image: nestjs_image
    container_name: nestjs_container
    depends_on:
      - postgres
    networks:
      - transcendance
    ports:
      - 3000:3000

  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendance
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pg-admin:/var/lib/pgadmin
    networks:
      - transcendance
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

volumes:
  pg-admin:
    driver: local

  db-data:
    driver: local